Pull changes and clippy
edfloreshz/devmode pull request #24
Opened 2022-08-05 00:32 UTC by Kedap

fix #22

2022-08-05 04:01 UTC, edfloreshz commented on src/cli.rs
> +                } else if let Some(..) = add {
If you don't need the `T` inside an `Option<T>`, it is recommended to use `is_some()`.

```suggestion
                } else if add.is_some() {
```

2022-08-05 04:01 UTC, edfloreshz commented on src/cli.rs
> +                } else if let Some(..) = remove {
Same here.
```suggestion
                } else if remove.is_some() {
```

2022-08-05 04:03 UTC, edfloreshz commented on src/cli.rs
> +        about = "Updates a project.",
```suggestion
        about = "Fetch the latest changes for a project.",
```

2022-08-05 04:03 UTC, edfloreshz requested changes
Please review some of the comments before we merge this, good job! 👍🏼

2022-08-05 22:01 UTC, Kedap commented
It seems that it was my mistake for not verifying well what [clippy said](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap) and not completely refactoring

2022-08-05 22:06 UTC, edfloreshz commented
No worries, you can do `cargo clippy--fix` to apply all the suggestions automatically, be sure to commit your changes before, since this might be a destructive action.

2022-08-06 02:07 UTC, edfloreshz commented
I tried to use `update` but got the following result:
![image](https://user-images.githubusercontent.com/22224438/183229402-a9f8d12e-31ec-4c55-b019-098b80e63b9e.png)
I had to pull the changes manually.

2022-08-06 02:09 UTC, edfloreshz commented on src/utils/project.rs
> +    if analysis.0.is_fast_forward() {
The error should be somewhere here.

2022-08-06 02:10 UTC, edfloreshz requested changes
Please let me know if you need any assistance.

2022-08-10 00:47 UTC, edfloreshz commented on src/utils/project.rs
>      println!("Update project {}... \n\n", name);
```suggestion
    println!("Updating project {}... \n\n", name);
```

2022-08-10 00:48 UTC, edfloreshz commented on src/utils/project.rs
>      // project.reset(&project.revparse_single("HEAD"), ResetType::Hard, None)?;
```suggestion

```

2022-08-10 00:57 UTC, edfloreshz commented on src/utils/git_pull.rs
> +pub fn pull(repo_paht: &Path) -> Result<()> {
```suggestion
pub fn pull(repo_path: &Path) -> Result<()> {
```

2022-08-10 00:59 UTC, edfloreshz commented on src/utils/git_pull.rs
> +use anyhow::Result;
```suggestion
use anyhow::{Result, Context};
```

2022-08-10 01:00 UTC, edfloreshz requested changes
Looking good, just a few changes and we're done!

2022-08-10 01:02 UTC, edfloreshz commented on src/utils/git_pull.rs
> +    let repo = Repository::open(repo_paht).expect(NO_PROJECT_FOUND);
```suggestion
    let repo = Repository::open(repo_path).with_context(|| NO_PROJECT_FOUND);
```

2022-08-10 02:42 UTC, merged

2022-08-10 02:42 UTC, edfloreshz commented
Thank you!